[package]
edition = "2021"
name = "rustsvg"
version = "0.1.0"
[dependencies]
# cv = "0.6.0"
ndarray-vision = "0.3.0"
ndarray = { version = "0.15.4", default-features = false }
image = "0.23.4"
imageproc = "0.22.0"
criterion = "0.3.2"
png = "0.17.2"
# 
